version: "3.3"

services:
  filelisting:
    user: "${U_ID}:${G_ID}"
    build:
      context: .
      args:
        port: "9010"
        host: "zieger.dev/files"
        hostPath: "files"
        user_id: ${U_ID}
        group_id: ${G_ID}
    container_name: "filelisting"
    restart: unless-stopped
    networks:
      - default
    expose:
      - 9010
    volumes:
      - "~/files:/home/filelisting/files"
    labels:
      - "traefik.enable=true"
      - "traefik.port=9010"
      - "traefik.http.routers.filelisting.rule=(Host(`zieger.dev`) && PathPrefix(`/files`))"
      - "traefik.http.routers.filelisting.entrypoints=websecure"
      - "traefik.http.routers.filelisting.tls.certresolver=myresolver"
      - "traefik.http.routers.filelisting.middlewares=log4shell, autodetect, compression, ratelimit"

networks:
  default:
    external:
      name: web
